"""Built-in LS-RAG workflows (current + historical compatibility revisions)."""

from __future__ import annotations

from typing import Final

from src.contracts.workflow.models import WorkflowDefinition
from src.workflows.builtin_scatter import BUILTIN_NS1_PRE_MARKDOWN_SCATTER_COMPATIBILITY_WORKFLOW
from src.workflows.kind_family import (
    BUILTIN_HTTP_RESOURCE_KIND_WORKFLOW,
    BUILTIN_INLINE_KIND_WORKFLOW,
    BUILTIN_KIND_WORKFLOWS,
    BUILTIN_LOCAL_OBJECT_KIND_WORKFLOW,
    SOURCE_KIND_WORKFLOW_KEYS,
)
from src.workflows.kind_family_v1_compat import BUILTIN_KIND_V1_COMPATIBILITY_WORKFLOWS
from src.workflows.lsrag_definition import (
    BUILTIN_BROWSER_PRINT_PDF_INTAKE_WORKFLOW,
    BUILTIN_DOC_LLM_INTAKE_WORKFLOW,
    BUILTIN_HTTP_BROWSER_INTAKE_WORKFLOW,
    BUILTIN_HTTP_BROWSER_WEB_LLM_INTAKE_WORKFLOW,
    BUILTIN_HTTP_PDF_INTAKE_WORKFLOW,
    BUILTIN_HTTP_STATIC_INTAKE_WORKFLOW,
    BUILTIN_HTTP_WEB_LLM_INTAKE_WORKFLOW,
    BUILTIN_LOCAL_OBJECT_INTAKE_WORKFLOW,
    BUILTIN_LOCAL_OCR_INTAKE_WORKFLOW,
    BUILTIN_LOCAL_PDF_INTAKE_WORKFLOW,
    BUILTIN_LOCAL_PDF_LLM_INTAKE_WORKFLOW,
    BUILTIN_NS1_PRE_MARKDOWN_COMPATIBILITY_WORKFLOWS,
    BUILTIN_SINGLE_INTAKE_LSRAG_WORKFLOW,
    BUILTIN_SOURCE_PROFILE_WORKFLOWS,
    BUILTIN_VISION_REJECTION_INTAKE_WORKFLOW,
    SINGLE_SOURCE_PROFILE_WORKFLOW_KEYS,
)
from src.workflows.lsrag_historical import (
    BUILTIN_EXECUTION_COMPATIBILITY_WORKFLOWS as BUILTIN_HISTORICAL_EXECUTION_COMPATIBILITY_WORKFLOWS,
)
from src.workflows.lsrag_historical import (
    HISTORICAL_SINGLE_INTAKE_LSRAG_WORKFLOW_V1,
    HISTORICAL_SINGLE_INTAKE_LSRAG_WORKFLOW_V2,
)

BUILTIN_WORKFLOWS: Final[tuple[WorkflowDefinition, ...]] = (
    *BUILTIN_KIND_WORKFLOWS,
    BUILTIN_SINGLE_INTAKE_LSRAG_WORKFLOW,
    *BUILTIN_SOURCE_PROFILE_WORKFLOWS,
)

BUILTIN_EXECUTION_COMPATIBILITY_WORKFLOWS: Final[tuple[WorkflowDefinition, ...]] = (
    *BUILTIN_HISTORICAL_EXECUTION_COMPATIBILITY_WORKFLOWS,
    *BUILTIN_NS1_PRE_MARKDOWN_COMPATIBILITY_WORKFLOWS,
    BUILTIN_NS1_PRE_MARKDOWN_SCATTER_COMPATIBILITY_WORKFLOW,
)

# NHX1 keeps the pre-existing 16-plan denominator stable while the leaf-worker
# composition explicitly opts into the three checked-in kind-family rev1
# manifests needed for old-pin exact replay.
BUILTIN_NHX1_EXECUTION_COMPATIBILITY_WORKFLOWS: Final[tuple[WorkflowDefinition, ...]] = (
    *BUILTIN_EXECUTION_COMPATIBILITY_WORKFLOWS,
    *BUILTIN_KIND_V1_COMPATIBILITY_WORKFLOWS,
)

__all__ = [
    "BUILTIN_DOC_LLM_INTAKE_WORKFLOW",
    "BUILTIN_BROWSER_PRINT_PDF_INTAKE_WORKFLOW",
    "BUILTIN_EXECUTION_COMPATIBILITY_WORKFLOWS",
    "BUILTIN_NHX1_EXECUTION_COMPATIBILITY_WORKFLOWS",
    "BUILTIN_HTTP_BROWSER_INTAKE_WORKFLOW",
    "BUILTIN_HTTP_RESOURCE_KIND_WORKFLOW",
    "BUILTIN_INLINE_KIND_WORKFLOW",
    "BUILTIN_KIND_WORKFLOWS",
    "BUILTIN_KIND_V1_COMPATIBILITY_WORKFLOWS",
    "BUILTIN_HTTP_BROWSER_WEB_LLM_INTAKE_WORKFLOW",
    "BUILTIN_HTTP_PDF_INTAKE_WORKFLOW",
    "BUILTIN_HTTP_STATIC_INTAKE_WORKFLOW",
    "BUILTIN_HTTP_WEB_LLM_INTAKE_WORKFLOW",
    "BUILTIN_LOCAL_OBJECT_INTAKE_WORKFLOW",
    "BUILTIN_LOCAL_OBJECT_KIND_WORKFLOW",
    "BUILTIN_LOCAL_OCR_INTAKE_WORKFLOW",
    "BUILTIN_LOCAL_PDF_INTAKE_WORKFLOW",
    "BUILTIN_LOCAL_PDF_LLM_INTAKE_WORKFLOW",
    "BUILTIN_SINGLE_INTAKE_LSRAG_WORKFLOW",
    "BUILTIN_SOURCE_PROFILE_WORKFLOWS",
    "BUILTIN_VISION_REJECTION_INTAKE_WORKFLOW",
    "BUILTIN_WORKFLOWS",
    "HISTORICAL_SINGLE_INTAKE_LSRAG_WORKFLOW_V1",
    "HISTORICAL_SINGLE_INTAKE_LSRAG_WORKFLOW_V2",
    "SINGLE_SOURCE_PROFILE_WORKFLOW_KEYS",
    "SOURCE_KIND_WORKFLOW_KEYS",
]
